version: '3'
services:

   ios-usage-prometheus-exporter:
    build: .
    ports:
     - "80:80"
     - "9090:9090"
    environment:
     - API_KEY=0123456789
     - PROMETHEUS_PORT=9090
     - WEBSERVER_PORT=80